CSV reading facilities
MinePlanner/Tubul pull request #10
Opened 2023-02-08 20:49 UTC by bigbadrat

Trabajo en curso para leer archivos csv. Ya está bastante potable, pero me faltan casos de uso mas claros/realistas para estar seguro que esto es suficiente. Por ejemplo, valdrá la pena un read_csv desde un stream? desde un string? Algo mas facil en CSVColumns?
Tambien, estaba probando con un csv que saqué de mines repo (el mas grande que encontré) para el example, que claramente no quiero subir acá... alguna recomendación de como solucionar eso? Quizás agregar un csv como string y el overload para leerlo asi, de forma que example quede bien auto-contenido?

2023-02-09 14:55 UTC, nloira requested changes

2023-02-09 14:55 UTC, nloira commented on apps/example1/example1.cpp
> +std::string getMemUsage()
Esta función es un buen candidato pa mover a TU::Memory ("Memory" como concepto, no es que exista ese namespace)

2023-02-09 14:55 UTC, nloira commented on api/tubul.h
> +	struct CSVColumns;
Más que un CSVColumns, yo le llamaría a esto un "DataFrame", o algo similar. Algo que refleje lo que contiene, más que cuál fue su origen. Podría haber sido leído de, por ejemplo, una base de datos!

2023-02-09 14:55 UTC, nloira commented on api/tubul.h
> +	struct CSVColumns;
Mi opinión es que debería devolver algo similar a los ejemplos de `TU::Data`

2023-02-09 14:55 UTC, nloira commented on tubul/tubul_parse_csv.h
> +using DataColumn = std::variant<std::monostate, DoubleColumn, IntegerColumn, StringColumn>;
choro `std::monostate`! No lo cachaba.

2023-02-09 14:55 UTC, nloira commented on tubul/tubul_parse_csv.cpp
> +			//Do some error handling? Likely just log and get out
porfa agregar este manejo de error! al menos un print por ahora

2023-02-09 15:02 UTC, bigbadrat commented on apps/example1/example1.cpp
> +std::string getMemUsage()
Definitivamente.... si lo puse ahi mas que nada para mirar _algo_ de la memoria y ver si me hace sentido.... de ahi podemos hacer mejores cosas y mas ordenadas

2023-02-09 15:03 UTC, bigbadrat commented on tubul/tubul_parse_csv.h
> +using DataColumn = std::variant<std::monostate, DoubleColumn, IntegerColumn, StringColumn>;
yo me demoré mucho en cacharlo y es muy util

2023-02-09 15:04 UTC, bigbadrat commented on tubul/tubul_parse_csv.cpp
> +			//Do some error handling? Likely just log and get out
ahh es que queria ponerlo con el logger :D ... le agrego un std::cout por ahora....

En todo caso recordar que esto NO ESTA CABLEADO. Nada lo está usando por eso no le puse mas cariño tampoco

2023-02-09 15:18 UTC, bigbadrat commented on api/tubul.h
> +	struct CSVColumns;
Definitivamente puedo cambiarle el nombre... tengo unas dudas sobre otros métodos de dataframe... Voy a subir algo intermedio por ahora porque si usamos directamente TU::Data van a haber otros problemas de include.

2023-02-09 17:49 UTC, bigbadrat commented on api/tubul.h
> +	struct CSVColumns;
Nombre cambiado a DataFrame. Despues puedo seguir sacándolo a otro header (TU::Data?) para que sea mas independiente

2023-03-14 15:56 UTC, nloira approved these changes

2023-03-14 15:57 UTC, merged