Dev csv2
MinePlanner/Tubul pull request #16
Opened 2023-03-22 14:39 UTC by bigbadrat

A lot of small improvements for dataframe reading/handling and code readability.

2023-03-22 20:44 UTC, nloira requested changes

2023-03-22 20:44 UTC, nloira commented on api/tubul.h
> +	 * or a Columnrequest object, you can choose the columns that will be populated
Columnrequest - > ColumnRequest

2023-03-22 20:44 UTC, nloira commented on api/tubul.h
> +	 * in the dataframe (the rest is dropped) and even choose some the type of the
choose the types of the columns

2023-03-22 20:44 UTC, nloira commented on tubul/tubul_parse_csv.cpp
> + * and retrieve the selected columns into vectors. This is done by passing a
esa "a" al final sobra

2023-03-22 20:44 UTC, nloira commented on tubul/tubul_parse_csv.h
> +	RowHeaders rowHeaders;
por qué no usar booleans para estos dos?

2023-03-22 21:04 UTC, bigbadrat commented on tubul/tubul_parse_csv.h
> +	RowHeaders rowHeaders;
porque los booleans en el vacio no tienen significado, en cambio si tu ves "ColumnHeaders::YES, RowHeaders::NO" es mucho mas claro que leer "true, false"

2023-03-22 21:07 UTC, bigbadrat commented on api/tubul.h
> +	 * or a Columnrequest object, you can choose the columns that will be populated
fixed

2023-03-22 21:07 UTC, bigbadrat commented on api/tubul.h
> +	 * in the dataframe (the rest is dropped) and even choose some the type of the
Fixed!

2023-03-22 21:07 UTC, bigbadrat commented on tubul/tubul_parse_csv.cpp
> + * and retrieve the selected columns into vectors. This is done by passing a
Fixed

2023-03-23 20:29 UTC, nloira approved these changes

2023-03-23 20:30 UTC, merged