Added template trickery for easier management of tuples in unordered …
MinePlanner/Tubul pull request #24
Opened 2023-04-04 17:02 UTC by bigbadrat

…maps and things that require hashes. If the tuple is made of things that do have an std::hash, they can be used with the TU::hash object

2023-04-10 20:58 UTC, nloira requested changes

2023-04-10 20:58 UTC, nloira commented on tubul/tubul_types.h
> +namespace TU {
por qué reabrir el namespace `TU`?

2023-04-10 20:58 UTC, nloira commented on tubul/tubul_types.h
> +namespace TU {
Si mal no recuerdo, el formato en el .clang-format del repo, es que el contenido dentro de un namespace *no va indentado*.

2023-04-10 20:58 UTC, nloira commented on tubul/tubul_types.h
> +        // Code from boost
Qué implicancia tiene que tomemos el código de boost? tenemos que agregar esa licencia en alguna parte?

2023-04-12 21:37 UTC, bigbadrat commented on tubul/tubul_types.h
> +namespace TU {
Mmmm será algo raro con clion? la verdad es que ya me cansé de pelear con clion y lehago caso no mas. Voy a revisar eso. Sobre reabrir el namespace.... no se, creo que estuve moviendo cosas de un lado para otro y se me olvidó mezclar los namespaces.

2023-04-12 21:38 UTC, bigbadrat commented on tubul/tubul_types.h
> +        // Code from boost
Que yo sepa, no.... ese metodo es bien famoso porque hay pocos "simples" para mezclar hashes y que tengan algunas propiedades razonables. Puedo sacar el resto del comentario que es literalmente copiado de stack overflow

2023-04-13 13:21 UTC, bigbadrat reviewed
Borré el namespace TU que estaba de mas.

2023-04-13 17:29 UTC, nloira approved these changes

2023-04-13 17:49 UTC, merged