New clion folder to ignore.
MinePlanner/Tubul pull request #27
Opened 2023-04-21 20:44 UTC by bigbadrat

2023-04-23 04:00 UTC, nloira requested changes

2023-04-23 04:00 UTC, nloira commented on .gitignore
> +/.cache/clangd/*
Yo dejaría todo el directorio .cache afuera, no?
Y el glob no es necesario. con:
`.cache/`
debería ser suficiente. Creo.

2023-04-24 13:53 UTC, bigbadrat commented on .gitignore
> +/.cache/clangd/*
o sea.... me tiene medio cachudo esto porque de repente me salio que tenia como 47 archivos en mi repo que podian ser agregados a git.... me tinca que salio de un update de clion que hice hace poco....  como no tengo claro de donde diablos salieron quise ser relativamente cauto, pero estoy de acuerdo que  .cache/ deberia ser suficiente....

2023-04-25 00:09 UTC, nloira approved these changes

2023-04-25 13:23 UTC, merged