Adding overloads for std::string_views for tolower/upper to make life…
MinePlanner/Tubul pull request #58
Opened 2024-07-01 22:40 UTC by bigbadrat

… easier.

2024-07-23 16:43 UTC, nloira requested changes

2024-07-23 16:43 UTC, nloira commented on tubul/tubul_logger.h
> +                getInstance().safelog(level_, parts_.str());
Suena a que estás comparando dos veces el mismo tag, no? Error de copy&paste?
`constexpr (std::is_same_v<TagType, LogStreamNormalTag> )`

2024-07-23 16:43 UTC, nloira commented on tubul/tubul_logger.h
> +                getInstance().safelog(level_, parts_.str());
como que el else if debería ser contra `LogStreamThreadSafeTag`

2024-07-23 16:47 UTC, bigbadrat commented on tubul/tubul_logger.h
> +                getInstance().safelog(level_, parts_.str());
me suena a que tienes razon ... revisaré en un momento y actualizo

2024-07-29 22:11 UTC, nloira approved these changes

2024-07-30 13:38 UTC, merged